CONNECTION_STRING = "udp:127.0.0.1:14540"
MSG_HEARTBEAT = "HEARTBEAT"
MSG_ACK = "COMMAND_ACK"
MSG_GPS = "GPS_RAW_INT"
MSG_SYS = "SYS_STATUS"
MSG_HUD = "VFR_HUD"
MSG_LOC_POSIT_NED = "LOCAL_POSITION_NED"
TARGET_POSITION_GROUND = (0,0,0)